---
# tasks file for cron_job
- name: Copy script file to folder
  copy: src={{ script_name }} dest={{ destin_folder }}

- name: Cron job
  ansible.builtin.cron:
    name: "check digest"
    minute: "2"
    job: "{{ destin_folder }}/{{ script_name }}"