---
# tasks file for cron_job
- name: Copy script file to folder
  copy: src={{ script_name }} dest={{ destin_folder }} mode=0551

- name: Cron job
  ansible.builtin.cron:
    user: "ec2-user"
    name: "check digest"
    minute: "2"
    job: "{{ destin_folder }}/{{ script_name }}"